### ISSUE TITLE
Recommend real fix rather than disabling check

### ISSUE THREAD

**Issue by srl295** [unicode-org/jira-github-pr-check#12]
The checker tool's page ( https://us-central1-festive-cistern-138116.cloudfunctions.net/icu-jira-github-pr-check-test/info/unicode-org/cldr/13 ) currently says:

> Commit a390c8f is for CLDR-1234, but the PR is for CLDR-11910; to disable, set DISABLE_JIRA_ISSUE_MATCH=true in the PR description

This page should recommend _fixing_ the bad commit message as the first resort rather than bypassing the check.

// @macchiati

**Comment by sffc** [comment]
Fix deployed.
