### ISSUE TITLE
indicate if it's "rebase and merge" ready?

### ISSUE THREAD

**Issue by srl295** [unicode-org/jira-github-pr-check#3]
Could the hook indicate whether *all* commits are eligible for a "rebase and merge"? i.e. if they all mention the same JIRA id AND include the PR URL?

**Comment by srl295** [comment]
^ really, it's a small step from here to just asking the hook to do exactly the kind of merge we want, and FIX the commits.

**Comment by sffc** [comment]
The latest changes look at commit message formats and enforce them.
