### ISSUE TITLE
please rename the default branch of this repo from "master" to "main"

### ISSUE THREAD

**Issue by markusicu** [unicode-org/jira-github-pr-check#41]
I believe that this is now the last of the unicode-org repos which is still using "master". (Except for archived repos.)
According to the notes on our tracking spreadsheet, this was tried before and "changed back to master due to GCP bug".
Could someone please look at what bug that was and whether we can get past it now?

@srl295 @sffc

**Comment by sffc** [comment]
The bug links which Googlers can view are [here](https://metabug.corp.google.com/entity/84317483) and [here](https://b.corp.google.com/issues/201119736). It does not appear that they have been resolved yet, but I just pinged the team for an update.

**Comment by sffc** [comment]
The GCP team helped me resolve the issue, so I've now changed the default branch name to "main".
